sudo: required

notifications:
  email: false

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t nskins/boomer-central .

script:
  - docker run -p 3000:3000 nskins/boomer-central /bin/sh -c "npm test"